version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.Date.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: SdTtiuKPbo/RJdnNAKEzS620PxAMmrZh1OKqLNsW69zZKa5u1KH32E2Mob9h8NfK
  artifact: /.*(\.|\.s)nupkg/
